ToDoApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls")),
]

todo/urls.py
from django.urls import path

from . import views

app_name = "todo_app"

urlpatterns = [
    path('', views.home, name = "home"),
    path('<int:item_id>/delete/', views.delete, name = "delete")
]

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    item = models.CharField(max_length=200)
    added_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item

todo/views.py
from django.shortcuts import get_object_or_404, render, redirect

from .models import Todo

# Create your views here.
def home(request):
    if request.method == "POST":
        todo_item = request.POST.get('todo')
        Todo.objects.create(item = todo_item)
    
    todo_list = Todo.objects.all().order_by("-added_date")
    return render(request, 'todo/home.html', {"todo_list": todo_list})

def delete(request, item_id):
    get_object_or_404(Todo, pk=item_id).delete()
    # obj.delete()
    return redirect('todo_app:home')
    

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo App Django</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="/" class="navbar-brand">To Do App</a>
        </div>
    </nav>
    <div class="container">
        {% block content %}
    
        {% endblock content %}
    </div>
</body>
</html>

todo/templates/todo/home.html
{% extends "base.html" %}

{% block content %}
    <div class="row mt-4">
        <div class="col">
            <h2>Add Item</h2>
            <form action="{% url 'todo_app:home' %}" method="POST" class="form-inline">
                {% csrf_token %}
                <input type="text" class="form-control mb-2 mr-sm-2" placeholder="type here..." name="todo" required>
                <button type="submit" class="btn btn-primary mb-2">Submit</button>
            </form>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
               {% for todo_item in todo_list %}
                    <li class="list-group-item">
                        {{todo_item.item}}
                        <a href="{% url 'todo_app:delete' todo_item.id %}" class=" float-right btn-sm btn btn-danger">Delete</a>
                    </li>
               {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}